# Development values for langgraph-agent
replicaCount: 1

image:
  repository: dukeman/langgraph
  tag: "latest"
  pullPolicy: Never  # Use local images for dev

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Disable autoscaling for dev
autoscaling:
  enabled: false

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Development-specific settings
env:
  OPENAI_API_KEY: ""

# Ingress configuration for development
ingress:
  enabled: true
  className: "traefik"
  hostname: "langgraph-agent-dev.leetserve.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-aws-prod"
    external-dns.alpha.kubernetes.io/hostname: "langgraph-agent-dev.leetserve.com"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "traefik"
  certManager:
    issuer: "letsencrypt-aws-prod"
  tls:
    enabled: true

# Pod annotations for development
podAnnotations:
  skaffold.dev/run-id: "{{ .Values.skaffoldRunId }}"

# Security context for development
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

podSecurityContext:
  fsGroup: 1000
